%parent(Parent,Child): Parent is a parent (mother or father) of Child
parent(queen_elizabeth_II,prince_charles).
parent(prince_phillip,prince_charles).
parent(queen_elizabeth_II,princess_anne).
parent(prince_phillip,princess_anne).
parent(queen_elizabeth_II,prince_andrew).
parent(prince_phillip,prince_andrew).
parent(queen_elizabeth_II,prince_edward).
parent(prince_phillip,prince_edward).
parent(prince_charles,prince_william).
parent(prince_charles,prince_harry).
parent(princess_diana,prince_william).
parent(princess_diana,prince_harry).
parent(princess_anne,peter_phillips).
parent(princess_anne,zara_phillips).
parent(captain_mark_phillips,peter_phillips).
parent(captain_mark_phillips,zara_phillips).
parent(prince_andrew,princess_beatrice).
parent(prince_andrew,princess_eugenie).
parent(sarah_ferguson,princess_beatrice).
parent(sarah_ferguson,princess_eugenie).
parent(prince_edward,james_viscount_severn).
parent(prince_edward,lade_louise_mountbatten_windsor).
parent(sophie_rhys-jones,james_viscount_severn).
parent(sophie_rhys-jones,lade_louise_mountbatten_windsor).
parent(prince_william,prince_george).
parent(prince_william,princess_charlotte).
parent(kate_middleton,prince_george).
parent(kate_middleton,princess_charlotte).
parent(peter_phillips,savannah_phillips).
parent(peter_phillips,isla_phillips).
parent(autumn_kelly,savannah_phillips).
parent(aytumn_kelly,isla_phillips).
parent(zara_phillips,mia_grace_tindall).
parent(mike_tindall,mia_grace_tindall).
%male(Person): Person's gender is male
male(prince_phillip).
male(prince_charles).
male(captain_mark_phillips).
male(timothy_laurence).
male(prince_andrew).
male(prince_edward).
male(prince_william).
male(prince_harry).
male(peter_phillips).
male(mike_tindall).
male(james_viscount_severn).
male(prince_george).
male(mia_grace_tindall).
%female(Person): Person's gender is female
female(queen_elizabeth_II).
female(princess_diana).
female(camilla_parker_bowles).
female(princess_anne).
female(sarah_ferguson).
female(sophie_rhys-jones).
female(kate_middleton).
female(autumn_kelly).
female(zara_phillips).
female(princess_beatrice).
female(princess_eugenie).
female(lady_louise_mountbatten_windsor).
female(princess_charlotte).
female(savannah_phillips).
female(isla_phillips).
%married(Person,Person): 2 Persons are married
married(queen_elizabeth_II,prince_phillips).
married(prince_charles,camilla_parker_bowles).
married(princess_anne,timothy_laurence).
married(sophie_rhys-jones,prince_edward).
married(prince_william,kate_middleton).
married(autumn_kelly,peter_phillips).
married(zara_phillips,mike_tindall).
%divorced(Person,Person): 2 Persons had been married, then divorced
divorced(princess_diana,prince_charles).
divorced(captain_mark_phillips,princess_anne).
devorced(sarah_ferguson,prince_andrew).
%other relationships
%2 generations
husband(Person,Wife):-
    married(Wife,Person);married(Person,Wife),
    male(Person).
wife(Person,Husband):-
    married(Husband,Person);married(Person,Husband),
    female(Person).
father(Parent,Child):-
    parent(Parent,Child),
    male(Parent).
mother(Parent,Child):-
    parent(Parent,Child),
    female(Parent).
child(Child,Parent):-
    parent(Parent,Child).
son(Child,Parent):-
    child(Child,Parent),
    male(Child).
daughter(Child,Parent):-
    child(Child,Parent),
    female(Child).
%3 generations
grandparent(GP,GC):-
    parent(GP,P),
    parent(P,GC).
grandmother(GM,GC):-
    grandparent(GM,GC),
    female(GM).
grandfather(GF,GC):-
    grandparent(GF,GC),
    male(GF).
grandchild(GC,GP):-
    grandparent(GP,GC).
grandson(GS,GP):-
    grandchild(GS,GP),
    male(GS).
granddaughter(GD,GP):-
    grandchild(GD,GP),
    female(GD).
%1 generation
sibling(Person1,Person2):-
    parent(P,Person1),
    parent(P,Person2),
    Person1 \= Person2.
brother(Person,Sibling):-
    sibling(Person,Sibling),
    male(Person).
sister(Person,Sibling):-
    sibling(Person,Sibling),
    female(Person).
%others
aunt(Person,NieceNephew):-
    parent(OPerson,NieceNephew),
    sister(Person,OPerson).
uncle(Person,NieceNephew):-
    parent(OPerson,NieceNephew),
    brother(Person,OPerson).
niece(Person,AuntUncle):-
    aunt(AuntUncle,Person);uncle(AuntUncle,Person),
    female(Person).
nephew(Person,AuntUncle):-
    aunt(AuntUncle,Person);uncle(AuntUncle,Person),
    male(Person).
